In [1]:
import numpy as np
from scipy.linalg import svd

In [2]:
def calculate_SVD(A):
    # Tính SVD của ma trận A
    U, s, Vt = svd(A)
    
    # Tạo ma trận Σ từ vector s
    k = len(s)
    k_zeros_matrix = np.zeros((k, k))
    np.fill_diagonal(k_zeros_matrix, s)
    Sigma = np.zeros((A.shape[0], A.shape[1]))
    Sigma[:k, :k] = k_zeros_matrix

    return U, Vt, Sigma, s

def get_SVD_by_k(U, Vt, Sigma, k):
    # Giữ lại k dòng và k cột đầu tiên của ma trận Σ để tạo thành Σk
    Sigma_k = Sigma[:k, :k]

    # Giữ lại k cột đầu tiên của ma trận U để tạo ra Uk
    U_k = U[:, :k]
    
    # Giữ lại k hàng đầu tiên của ma trận V chuyển vị để tạo ra VkT
    V_kT = Vt[:k, :]

    return U_k, V_kT, Sigma_k

def calculate_compact_SVD(A):
    U, Vt, Sigma, s = calculate_SVD(A)
    # Số giá trị kì dị khác 0
    r = np.count_nonzero(s)

    U_r, V_rT, Sigma_r = get_SVD_by_k(U, Vt, Sigma, r)

    return U_r, V_rT, Sigma_r

def calculate_truncated_SVD(A, k):
    U, Vt, Sigma, s = calculate_SVD(A)
    U_k, V_kT, Sigma_k = get_SVD_by_k(U, Vt, Sigma, k)

    # Tính phần trăm lượng thông tin được giữ lại
    total_information = np.sum(s**2)
    retained_information = np.sum(s[:k]**2)
    retained_percentage = (retained_information / total_information) * 100
    
    return U_k, V_kT, Sigma_k, retained_percentage

def get_truncated_SVD_retained_information(A, threshold=90):
    U, Vt, Sigma, s = calculate_SVD(A)
    
    # Tìm số lượng giá trị kì dị cần giữ lại để đạt được ngưỡng thông tin
    total_information = np.sum(s**2)
    retained_information = 0
    k = 0
    for i in range(len(s)):
        retained_information += s[i]**2
        k += 1
        if (retained_information / total_information) * 100 >= threshold:
            break
            
    U_k, V_kT, Sigma_k = get_SVD_by_k(U, Vt, Sigma, k)

    return U_k, V_kT, Sigma_k, k

In [3]:
# Bài tập 1:
A = np.array([[1, 0, 0, 0, 2], 
              [0, 0, 3, 0, 0], 
              [0, 0, 0, 0, 0],
              [0, 2, 0, 0, 0]])
U, Vt, Sigma, _ = calculate_SVD(A)
print("Ma trận U:")
print(U)
    
print("Ma trận V chuyển vị:")
print(Vt)
    
print("Ma trận Σ:")
print(Sigma)

Ma trận U:
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]]
Ma trận V chuyển vị:
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [ 0.         -1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]
Ma trận Σ:
[[3.         0.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.         0.        ]
 [0.         0.         2.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [4]:
# Bài tập 2:
A = np.array([[1, 0, 0, 0, 2], 
              [0, 0, 3, 0, 0], 
              [0, 0, 0, 0, 0],
              [0, 2, 0, 0, 0]])
U_r, V_rT, Sigma_r = calculate_compact_SVD(A)
print("Ma trận Ur:")
print(U_r)
    
print("Ma trận VrT:")
print(V_rT)
    
print("Ma trận Σr:")
print(Sigma_r)

Ma trận Ur:
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]
Ma trận VrT:
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [ 0.         -1.          0.          0.          0.        ]]
Ma trận Σr:
[[3.         0.         0.        ]
 [0.         2.23606798 0.        ]
 [0.         0.         2.        ]]


In [5]:
# Bài tập 3:
A = np.array([[1.01, 0.9, 0.2, 1.001, 0.3], 
              [0.2, 1.01, 0.3, 0.8, 0.4], 
              [1, 1.002, 2, 0.98, 2],
              [0.3, 2, 0.4, 1.01, 0.9],
              [1.1, 0.2, 0.03, 2, 0.87]])
k = 4
U_k, V_kT, Sigma_k, retained_percentage = calculate_truncated_SVD(A, k)
print("Ma trận Uk:")
print(U_k)
    
print("Ma trận VkT:")
print(V_kT)
    
print("Ma trận Σk:")
print(Sigma_k)

print(f"Phần trăm lượng thông tin giữ lại khi giữ lại {k} giá trị kì dị: {retained_percentage:.2f}%")

Ma trận Uk:
[[-0.32813554  0.32928789  0.08780746 -0.88098834]
 [-0.27374756  0.09123211  0.31504405  0.16061502]
 [-0.64816455 -0.65873014 -0.3795124  -0.04270121]
 [-0.46609071  0.0207275   0.71918456  0.25646457]
 [-0.4243012   0.66999341 -0.4814364   0.36119923]]
Ma trận VkT:
[[-0.35047463 -0.4780765  -0.35097791 -0.5344013  -0.48973477]
 [ 0.24274782 -0.05358443 -0.66685673  0.62343097 -0.32378718]
 [-0.3428965   0.86035897 -0.23658964 -0.1699711  -0.2394569 ]
 [-0.77612359 -0.16080247 -0.18212689  0.3391472   0.47284639]]
Ma trận Σk:
[[4.68190663 0.         0.         0.        ]
 [0.         1.79325215 0.         0.        ]
 [0.         0.         1.57960998 0.        ]
 [0.         0.         0.         0.54903356]]
Phần trăm lượng thông tin giữ lại khi giữ lại 4 giá trị kì dị: 99.89%


In [6]:
# Bài tập 4:
A = np.array([[1.01, 0.9, 0.2, 1.001, 0.3], 
              [0.2, 1.01, 0.3, 0.8, 0.4], 
              [1, 1.002, 2, 0.98, 2],
              [0.3, 2, 0.4, 1.01, 0.9],
              [1.1, 0.2, 0.03, 2, 0.87]])
threshold = 90
U_k, V_kT, Sigma_k, k = get_truncated_SVD_retained_information(A, threshold)
print("Ma trận Uk:")
print(U_k)
    
print("Ma trận VkT:")
print(V_kT)
    
print("Ma trận Σk:")
print(Sigma_k)

print(f"Số giá trị k cần giữ là: {k}")

Ma trận Uk:
[[-0.32813554  0.32928789  0.08780746]
 [-0.27374756  0.09123211  0.31504405]
 [-0.64816455 -0.65873014 -0.3795124 ]
 [-0.46609071  0.0207275   0.71918456]
 [-0.4243012   0.66999341 -0.4814364 ]]
Ma trận VkT:
[[-0.35047463 -0.4780765  -0.35097791 -0.5344013  -0.48973477]
 [ 0.24274782 -0.05358443 -0.66685673  0.62343097 -0.32378718]
 [-0.3428965   0.86035897 -0.23658964 -0.1699711  -0.2394569 ]]
Ma trận Σk:
[[4.68190663 0.         0.        ]
 [0.         1.79325215 0.        ]
 [0.         0.         1.57960998]]
Số giá trị k cần giữ là: 3
